# Generated by Django 4.2.4 on 2023-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataForm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=1)),
                ("age1", models.CharField(max_length=1)),
                ("age2", models.CharField(max_length=1)),
                ("unhurt", models.CharField(max_length=1)),
                ("dead", models.CharField(max_length=1)),
                ("hospitalized", models.CharField(max_length=1)),
                ("hurt_light", models.CharField(max_length=1)),
                ("men", models.CharField(max_length=1)),
                ("women", models.CharField(max_length=1)),
                ("departement", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="DataPred",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("departement", models.CharField(max_length=4)),
                ("age", models.IntegerField()),
                ("gender", models.IntegerField()),
                ("location", models.IntegerField()),
                ("intersection", models.IntegerField()),
                ("light", models.IntegerField()),
            ],
        ),
    ]
